language: node_js

node_js:
- "4"
- "0.12"

sudo: false

install:
  - npm install -g codecov
  - npm install
script:
  - npm test && codecov
  - npm run build
after_success:
  - if [[ `node -v` == v4* ]] && [[ "$TRAVIS_BRANCH" == "next" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      ./script/release.sh;
    fi
